return {
    LinearLayout,
    layout_width = "fill",
    layout_height = "fill",
    gravity = "center_horizontal",
    background = "#FFFFFF",
    background = "#FFFFFF",
    orientation = 1,
    paddingLeft = "16dp",
    paddingRight = "16dp",
    focusable = true,
    focusableInTouchMode = true,
    {
        ImageView,
        layout_height = "64dp",
        layout_width = "64dp",
        layout_marginTop= "120dp",
        src = "#main/logo.png",
    },
    {
        TextView,
        id = "tv_add_plugin",
        layout_height = "48dp",
        layout_width = "fill",
        layout_marginLeft = "24dp",
        layout_marginTop = "48dp",
        layout_marginBottom = "40dp",
        layout_marginRight = "24dp",
        gravity = "center",
        text = "URL | AGC | NEWS | CODE",
        textColor = "#9DAEBF",
        textSize = "12sp",
        background = "#F4F4F4",
    },
    {
        GridView,
        id = "gridView",
        layout_width = "fill",
        layout_marginLeft = "14dp",
        layout_marginRight = "14dp",
        numColumns = 5,
    },
}
