return {
    LinearLayout,
    layout_width = "fill",
    layout_height = "fill",
    gravity = "center",
    background = "#FFFFFF",
    fitsSystemWindows = true,
    orientation = 1,
    paddingLeft = "16dp",
    paddingRight = "16dp",
    focusable = true,
    focusableInTouchMode = true,
    {
        TextView,
        text = "Quark",
        textSize = "36sp",
        textColor = "#2979FB",
    },
    {
        TextView,
        id = "tv_add_plugin",
        layout_height = "48dp",
        layout_width = "fill",
        layout_marginLeft = "40dp",
        layout_marginTop = "64dp",
        layout_marginBottom = "40dp",
        layout_marginRight = "40dp",
        gravity = "center",
        text = "URL | AGC | NEWS | CODE",
        textColor = "#9DAEBF",
        textSize = "12sp",
        background = "#F4F4F4",
    },
    {
        GridView,
        id = "gridView",
        layout_width = "fill",
        numColumns = 5,
        layout_marginLeft = "40dp",
        layout_marginRight = "40dp",
    },
}